name: Deploy App

on:
  push:
    paths:
      - 'apps/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm ci
      - name: Deploy App
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          APP_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep ^apps/ | cut -d/ -f2 | uniq)
          if [ ! -z "$APP_PATH" ]; then
            npx tsx scripts/pipeline/deployApp.ts $APP_PATH
          fi
