name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_KRONE_SH_DNS_TOKEN: ${{ secrets.CLOUDFLARE_KRONE_SH_DNS_TOKEN }}

on:
  push:
    paths:
      - 'apps/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm ci
      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: '2'
          files: apps/**
      - name: Print Changed Files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "Changed file: $file"

            if [[ $file == apps/* ]]; then
            app=$(echo $file | cut -d'/' -f2)
            echo "Deploying $app"

              # Set up the app (this might include setting up environment variables, etc.)
              npx tsx scripts/cli.js setup $app

              npx tsx scripts/cli.js deploy $app
            else
              echo "$file was changed"
            fi
          done
      ## Preview Deployment
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
